/*
 * Logic 4
 * Copyright © 2026 Serge Benoliel. All rights reserved.
 * Proprietary software. Copying, modification, redistribution or exploitation without prior written authorization is prohibited.
 */
'use strict';
const $=s=>document.querySelector(s), app=$('#app'), toast=$('#toast'), timerEl=$('#timer');
const VERSION='2.1.0', SAVE_KEY='logic4-save-v1';
let current=null, tick=null, startedAt=0, elapsedBase=0, paused=false;
const DIFF={easy:'Facile',medium:'Moyen',hard:'Difficile',expert:'Expert'};
const PREF_KEY='logic4-prefs-v1';
function prefs(){try{let p=JSON.parse(localStorage.getItem(PREF_KEY)||'{}');return {theme:['auto','light','dark'].includes(p.theme)?p.theme:'auto',sound:p.sound!==false,queenAutoCross:p.queenAutoCross===true}}catch(_){return {theme:'auto',sound:true,queenAutoCross:false}}}
function savePrefs(p){try{localStorage.setItem(PREF_KEY,JSON.stringify(p))}catch(_){}applyPrefs()}
function resolvedTheme(){let p=prefs();return p.theme==='auto'?(window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):p.theme}
function applyPrefs(){let p=prefs(),theme=resolvedTheme();document.documentElement.dataset.theme=theme;document.documentElement.dataset.themeMode=p.theme;let meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==='dark'?'#171916':'#f4f1e9';let b=$('#themeBtn');if(b){b.textContent=theme==='dark'?'☾':'☀︎';b.setAttribute('aria-label',`Thème : ${p.theme}`)}}
function cycleTheme(){let p=prefs(),m={auto:'light',light:'dark',dark:'auto'};p.theme=m[p.theme];savePrefs(p);showToast(`Thème : ${{auto:'Automatique',light:'Clair',dark:'Sombre'}[p.theme]}`)}
function toggleSound(){let p=prefs();p.sound=!p.sound;savePrefs(p);showToast(p.sound?'Sons activés':'Sons désactivés');return p.sound}
function playTone(kind='tap'){if(!prefs().sound)return;try{let A=window.AudioContext||window.webkitAudioContext;if(!A)return;let c=new A(),o=c.createOscillator(),g=c.createGain(),now=c.currentTime;o.type='sine';o.frequency.value=kind==='win'?659:kind==='error'?180:420;g.gain.setValueAtTime(kind==='win'?.06:.025,now);g.gain.exponentialRampToValueAtTime(.001,now+(kind==='win'?.38:.12));o.connect(g);g.connect(c.destination);o.start(now);o.stop(now+(kind==='win'?.4:.13));setTimeout(()=>c.close().catch(()=>{}),600)}catch(_){}}
function settingsView(){
  if(current&&!current.completed)saveCurrent();stopTimer();timerEl.textContent='00:00';current=null;let p=prefs();
  app.innerHTML=`<section class="panel settings-panel"><div class="stats-head"><div><h1>Préférences</h1><p>Réglages enregistrés sur cet appareil.</p></div><button class="btn" id="settingsBack">Retour</button></div>
  <div class="setting-row"><span><b>Thème</b><small>Automatique, clair ou sombre</small></span><select id="themeSelect" class="difficulty"><option value="auto" ${p.theme==='auto'?'selected':''}>Automatique</option><option value="light" ${p.theme==='light'?'selected':''}>Clair</option><option value="dark" ${p.theme==='dark'?'selected':''}>Sombre</option></select></div>
  <div class="setting-row"><span><b>Sons discrets</b><small>Victoire et retours ponctuels</small></span><button class="btn" id="soundToggle">${p.sound?'Activés':'Désactivés'}</button></div>
  <div class="setting-row"><span><b>Données</b><small>Statistiques, défis et préférences restent locales.</small></span><button class="btn" id="storageInfo">Info</button></div></section>`;
  $('#settingsBack').onclick=home;$('#themeSelect').onchange=e=>{let q=prefs();q.theme=e.target.value;savePrefs(q)};$('#soundToggle').onclick=()=>{let on=toggleSound();$('#soundToggle').textContent=on?'Activés':'Désactivés'};$('#storageInfo').onclick=()=>modal('Données locales','Logic 4 ne nécessite aucun compte. Les parties, statistiques, défis quotidiens et préférences sont stockés dans le navigateur de cet appareil.');app.querySelectorAll('button').forEach(pressFeedback)
}
function resultText(c,seconds){let daily=c?.daily?' · Défi quotidien':'';return `Logic 4 — ${gameLabel(c.game)}${daily}\n${DIFF[c.diff]} · ${fmt(seconds)}${c.rating?` · score ${c.rating.score}`:''}\n✓ Terminé`}
function resultSvg(c,seconds){
  let bg=resolvedTheme()==='dark'?'#171916':'#f4f1e9',ink=resolvedTheme()==='dark'?'#f2efe7':'#22231f',muted=resolvedTheme()==='dark'?'#b8b5ad':'#6b6a64',accent='#397466',title=gameLabel(c.game).replace(/&/g,'&amp;');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080"><rect width="1080" height="1080" rx="80" fill="${bg}"/><circle cx="110" cy="112" r="22" fill="${accent}"/><text x="155" y="130" font-family="-apple-system,BlinkMacSystemFont,Arial" font-size="54" font-weight="700" fill="${ink}">Logic 4</text><text x="90" y="410" font-family="Georgia,serif" font-size="112" font-weight="700" fill="${ink}">${title}</text><text x="90" y="520" font-family="-apple-system,BlinkMacSystemFont,Arial" font-size="48" fill="${muted}">${DIFF[c.diff]}${c.daily?' · Défi quotidien':''}</text><text x="90" y="720" font-family="-apple-system,BlinkMacSystemFont,Arial" font-size="132" font-weight="800" fill="${ink}">${fmt(seconds)}</text><text x="90" y="820" font-family="-apple-system,BlinkMacSystemFont,Arial" font-size="42" fill="${accent}">✓ Terminé</text><text x="90" y="965" font-family="-apple-system,BlinkMacSystemFont,Arial" font-size="32" fill="${muted}">logic 4 · v${VERSION}</text></svg>`
}
async function shareResult(c,seconds){
  let text=resultText(c,seconds);
  try{
    if(typeof Blob!=='undefined'&&typeof File!=='undefined'&&navigator.share){
      let blob=new Blob([resultSvg(c,seconds)],{type:'image/svg+xml'}),file=new File([blob],`logic4-${c.game}-${localDay()}.svg`,{type:'image/svg+xml'});
      let fileOK=!navigator.canShare||navigator.canShare({files:[file]});
      if(fileOK){await navigator.share({title:'Logic 4',text,files:[file]});return}
    }
    if(navigator.share){await navigator.share({title:'Logic 4',text});return}
    if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);showToast('Résultat copié');return}
  }catch(e){
    if(e?.name==='AbortError')return;
    try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);showToast('Résultat copié');return}}catch(_){}
  }
  showToast('Partage non disponible')
}
function victoryOverlay(c,seconds){
  let old=$('#victory');if(old)old.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="victory" id="victory" role="dialog" aria-modal="true"><div class="victory-card"><div class="victory-burst" aria-hidden="true">✦</div><small>BRAVO</small><h2>${gameLabel(c.game)}</h2><div class="victory-time">${fmt(seconds)}</div><p>${DIFF[c.diff]}${c.daily?' · Défi quotidien':''}${c.rating?` · score ${c.rating.score}`:''}</p><div class="victory-actions"><button class="btn primary" id="shareResult">Partager</button><button class="btn" id="closeVictory">Continuer</button></div></div></div>`);
  $('#shareResult').onclick=()=>shareResult(c,seconds);$('#closeVictory').onclick=()=>$('#victory')?.remove();$('#victory').onclick=e=>{if(e.target.id==='victory')e.currentTarget.remove()};playTone('win');haptic(28)
}

const STATS_KEY='logic4-stats-v1', HISTORY_LIMIT=200;
function blankStats(){return {schema:1,started:0,solved:0,revealed:0,totalSolvedSeconds:0,byGame:{},history:[]}}
function safeStats(){
  let s=blankStats();
  try{
    let raw=JSON.parse(localStorage.getItem(STATS_KEY)||'null');
    if(raw&&typeof raw==='object'){
      s.started=Math.max(0,Number(raw.started)||0);s.solved=Math.max(0,Number(raw.solved)||0);
      s.revealed=Math.max(0,Number(raw.revealed)||0);s.totalSolvedSeconds=Math.max(0,Number(raw.totalSolvedSeconds)||0);
      s.byGame=raw.byGame&&typeof raw.byGame==='object'?raw.byGame:{};
      s.history=Array.isArray(raw.history)?raw.history.filter(x=>x&&['queens','tango','sudoku','patches'].includes(x.game)&&['easy','medium','hard','expert'].includes(x.diff)).slice(0,HISTORY_LIMIT):[];
    }
  }catch(_){}
  return s
}
function writeStats(s){try{localStorage.setItem(STATS_KEY,JSON.stringify(s))}catch(_){}}
function statBucket(s,g,d){
  if(!s.byGame||typeof s.byGame!=='object')s.byGame={};
  if(!s.byGame[g]||typeof s.byGame[g]!=='object')s.byGame[g]={};
  if(!s.byGame[g][d]||typeof s.byGame[g][d]!=='object')s.byGame[g][d]={started:0,solved:0,revealed:0,totalSeconds:0,best:null};
  let b=s.byGame[g][d];b.started=Math.max(0,Number(b.started)||0);b.solved=Math.max(0,Number(b.solved)||0);b.revealed=Math.max(0,Number(b.revealed)||0);b.totalSeconds=Math.max(0,Number(b.totalSeconds)||0);b.best=b.best==null?null:Math.max(0,Number(b.best)||0);return b
}
function localDay(ts=Date.now()){let d=new Date(ts),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function statsStart(c){
  if(!c||c.attemptId)return;
  c.attemptId=`${Date.now()}-${Math.random().toString(36).slice(2,9)}`;c.startedAt=Date.now();c.statsClosed=false;
  let s=safeStats(),b=statBucket(s,c.game,c.diff);s.started++;b.started++;writeStats(s)
}
function statsFinish(c,seconds,outcome){
  if(!c||c.statsClosed)return;c.statsClosed=true;
  let s=safeStats(),b=statBucket(s,c.game,c.diff),rec={id:c.attemptId||`${Date.now()}`,ts:Date.now(),day:localDay(),game:c.game,diff:c.diff,seconds:Math.max(0,Math.round(seconds)),outcome,score:c.rating?.score??null};
  if(outcome==='solved'){s.solved++;s.totalSolvedSeconds+=rec.seconds;b.solved++;b.totalSeconds+=rec.seconds;b.best=b.best==null?rec.seconds:Math.min(b.best,rec.seconds)}
  if(outcome==='revealed'){s.revealed++;b.revealed++}
  s.history.unshift(rec);s.history=s.history.slice(0,HISTORY_LIMIT);writeStats(s)
}
function closePreviousAttempt(){
  let c=current&&current.attemptId&&!current.completed?current:null,saved=!c?getSaved():null;
  if(!c&&saved?.current?.attemptId&&!saved.current.completed)c=saved.current;
  if(c&&!c.statsClosed)statsFinish(c,c===current?timerSeconds():(saved?.elapsed||0),'abandoned')
}
function statsSummary(){
  let s=safeStats(),success=s.started?Math.round(100*s.solved/s.started):0,avg=s.solved?Math.round(s.totalSolvedSeconds/s.solved):0;
  let days=[...new Set(s.history.filter(x=>x.outcome==='solved').map(x=>x.day))].sort().reverse(),streak=0;
  if(days.length){
    let cur=new Date();cur.setHours(0,0,0,0);let yday=new Date(cur);yday.setDate(yday.getDate()-1);
    if(days[0]===localDay(cur.getTime())||days[0]===localDay(yday.getTime())){
      let d=new Date(days[0]+'T12:00:00');for(let day of days){if(day!==localDay(d.getTime()))break;streak++;d.setDate(d.getDate()-1)}
    }
  }
  return {s,success,avg,streak}
}


const DAILY_KEY='logic4-daily-v1';
function hash32(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}}
function withSeed(seed,fn){let old=Math.random;Math.random=mulberry32(hash32(seed));try{return fn()}finally{Math.random=old}}
function dailyState(){try{let x=JSON.parse(localStorage.getItem(DAILY_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch(_){return {}}}
function saveDailyState(x){try{localStorage.setItem(DAILY_KEY,JSON.stringify(x))}catch(_){}}
function dailyKey(day,game){return `${day}:${game}`}
function markDaily(c,outcome,seconds){if(!c?.daily)return;let s=dailyState(),k=dailyKey(c.dailyDay,c.game),old=s[k]||{};s[k]={day:c.dailyDay,game:c.game,outcome,seconds:Math.round(seconds),completedAt:Date.now(),best:outcome==='solved'?(old.best==null?Math.round(seconds):Math.min(old.best,Math.round(seconds))):old.best??null};saveDailyState(s)}
function dailyProgress(day=localDay()){let s=dailyState(),games=['queens','tango','sudoku','patches'];return games.map(g=>s[dailyKey(day,g)]).filter(x=>x?.outcome==='solved').length}
function dailyCalendar(days=28){let s=dailyState(),out=[],d=new Date();d.setHours(12,0,0,0);for(let i=0;i<days;i++){let day=localDay(d.getTime()),n=['queens','tango','sudoku','patches'].filter(g=>s[dailyKey(day,g)]?.outcome==='solved').length;out.push({day,n});d.setDate(d.getDate()-1)}return out}
function dailyView(){
  if(current&&!current.completed)saveCurrent();stopTimer();timerEl.textContent='00:00';current=null;
  let day=localDay(),s=dailyState(),games=['queens','tango','sudoku','patches'],cards=games.map(g=>{let r=s[dailyKey(day,g)],done=r?.outcome==='solved';return `<button class="daily-game ${done?'done':''}" data-daily="${g}"><span>${{queens:'♛',tango:'☀︎',sudoku:'✎',patches:'▦'}[g]}</span><b>${gameLabel(g)}</b><small>${done?`✓ ${fmt(r.best??r.seconds)}`:'Jouer'}</small></button>`}).join('');
  let cal=dailyCalendar().reverse().map(x=>`<div class="day-dot level-${x.n}" title="${x.day} · ${x.n}/4"><span>${new Date(x.day+'T12:00:00').getDate()}</span></div>`).join('');
  app.innerHTML=`<section class="panel daily-panel"><div class="stats-head"><div><h1>Défi quotidien</h1><p>${new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'})} · ${dailyProgress(day)}/4 terminés</p></div><button class="btn" id="dailyBack">Retour</button></div><div class="daily-games">${cards}</div><h2>28 derniers jours</h2><div class="daily-calendar">${cal}</div><p class="daily-note">Chaque date produit les mêmes quatre grilles sur tous les appareils utilisant cette version. Difficulté quotidienne : Moyen.</p></section>`;
  $('#dailyBack').onclick=home;app.querySelectorAll('[data-daily]').forEach(b=>b.onclick=()=>launchDaily(b.dataset.daily,day));app.querySelectorAll('button').forEach(pressFeedback)
}
function launchDaily(game,day=localDay()){
  closePreviousAttempt();clearSaved();stopTimer();paused=false;setBusy(true);current={game,diff:'medium',daily:true,dailyDay:day};
  requestAnimationFrame(()=>{try{withSeed(`logic4-v1.6:${day}:${game}`,()=>{if(game==='queens')queens('medium');if(game==='tango')tango('medium');if(game==='sudoku')sudoku('medium');if(game==='patches')patches('medium')});current.daily=true;current.dailyDay=day;statsStart(current);startTimer(true,0,false);saveCurrent();haptic(8)}finally{setBusy(false)}})
}
const coarsePointer=()=>window.matchMedia&&window.matchMedia('(pointer:coarse)').matches;
function haptic(ms=12){try{if(navigator.vibrate)navigator.vibrate(ms)}catch(_){}}
function setBusy(on,label='Génération…'){document.body.classList.toggle('busy',!!on);let x=$('#busyOverlay');if(x){x.hidden=!on;let s=x.querySelector('span');if(s)s.textContent=label}}
function pressFeedback(el){if(!el)return;el.addEventListener('pointerdown',()=>el.classList.add('pressed'),{passive:true});for(let ev of ['pointerup','pointercancel','pointerleave'])el.addEventListener(ev,()=>el.classList.remove('pressed'),{passive:true})}

function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1400)}
function timerSeconds(){return elapsedBase+(!paused&&startedAt?Math.floor((Date.now()-startedAt)/1000):0)}
function renderTimer(){timerEl.textContent=fmt(timerSeconds())}
function startTimer(reset=true,initial=0,isPaused=false){stopTimer(false);elapsedBase=reset?initial:timerSeconds();paused=isPaused;startedAt=paused?0:Date.now();renderTimer();if(!paused)tick=setInterval(()=>{renderTimer();if(current)saveCurrent()},1000)}
function stopTimer(commit=true){if(commit&&!paused&&startedAt){elapsedBase=timerSeconds();startedAt=0}if(tick)clearInterval(tick);tick=null}
function togglePause(){if(!current||current.completed)return;if(paused){paused=false;startedAt=Date.now();tick=setInterval(()=>{renderTimer();if(current)saveCurrent()},1000);showToast('Chrono repris')}else{elapsedBase=timerSeconds();startedAt=0;paused=true;if(tick)clearInterval(tick);tick=null;showToast('Chrono en pause')}updatePauseButton();saveCurrent()}
function updatePauseButton(){let b=$('#pauseBtn');if(b)b.textContent=paused?'Reprendre':'Pause'}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rotGrid(grid){const n=grid.length;return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>grid[n-1-c][r]))}
function flipGrid(grid){return grid.map(r=>[...r].reverse())}
function transformGrid(grid,k){let g=grid.map(r=>[...r]);for(let i=0;i<k%4;i++)g=rotGrid(g);if(k>=4)g=flipGrid(g);return g}
function modal(title,html){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="sheet"><h2>${title}</h2>${html}<button class="btn primary" onclick="document.querySelector('#modal').remove()">Fermer</button></div></div>`)}
function plainCurrent(){if(!current)return null;let o={...current};for(let k of ['givens','empty'])if(o[k] instanceof Set)o[k]=[...o[k]];return o}
function saveCurrent(){if(!current||current.completed)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:VERSION,current:plainCurrent(),elapsed:timerSeconds(),paused,savedAt:Date.now()}))}catch(_){}}
function getSaved(){try{let x=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');return x&&x.current?x:null}catch(_){return null}}
function clearSaved(){try{localStorage.removeItem(SAVE_KEY)}catch(_){}}
$('#homeBtn').onclick=home;$('#themeBtn').onclick=cycleTheme;

function statsView(){
  if(current&&!current.completed)saveCurrent();stopTimer();timerEl.textContent='00:00';current=null;
  let {s,success,avg,streak}=statsSummary(),games=['queens','tango','sudoku','patches'];
  let rows=games.map(g=>{
    let bs=(g==='queens'?['easy','medium','hard','expert']:['easy','medium','hard']).map(d=>s.byGame?.[g]?.[d]).filter(Boolean),started=bs.reduce((a,b)=>a+(b.started||0),0),solved=bs.reduce((a,b)=>a+(b.solved||0),0),total=bs.reduce((a,b)=>a+(b.totalSeconds||0),0),best=bs.map(b=>b.best).filter(v=>v!=null);
    return `<div class="stat-game"><b>${gameLabel(g)}</b><span>${solved}/${started} résolues</span><span>${solved?fmt(Math.round(total/solved)):'—'} moyen</span><span>${best.length?fmt(Math.min(...best)):'—'} record</span></div>`
  }).join('');
  let hist=s.history.slice(0,20).map(x=>`<div class="history-row"><span><b>${gameLabel(x.game)}</b> · ${DIFF[x.diff]}</span><span>${x.outcome==='solved'?'Résolu':x.outcome==='revealed'?'Solution vue':x.outcome==='abandoned'?'Abandonné':'Terminé'} · ${fmt(x.seconds)}</span><small>${new Date(x.ts).toLocaleDateString('fr-FR')}</small></div>`).join('')||'<p class="empty-state">Aucune partie terminée pour le moment.</p>';
  app.innerHTML=`<section class="panel stats-panel"><div class="stats-head"><div><h1>Statistiques</h1><p>Progression enregistrée uniquement sur cet appareil.</p></div><button class="btn" id="statsBack">Retour</button></div>
  <div class="stat-kpis"><div><strong>${s.solved}</strong><span>résolues</span></div><div><strong>${success}%</strong><span>réussite</span></div><div><strong>${avg?fmt(avg):'—'}</strong><span>temps moyen</span></div><div><strong>${streak}</strong><span>série de jours</span></div></div>
  <h2>Par jeu</h2><div class="stat-games">${rows}</div><h2>Historique récent</h2><div class="history-list">${hist}</div></section>`;
  $('#statsBack').onclick=home;app.querySelectorAll('button').forEach(pressFeedback)
}
function home(){if(current&&!current.completed)saveCurrent();stopTimer();timerEl.textContent='00:00';current=null;let saved=getSaved();app.innerHTML=`<section class="hero"><h1>Quatre jeux.<br>Une pause logique.</h1><p>Inspirés des mécaniques de Queens, Tango, Mini Sudoku et Patches. Fonctionne hors ligne après le premier chargement.</p></section>${saved?`<button class="resume-card" id="resumeBtn"><b>Reprendre ${gameLabel(saved.current.game)}</b><span>${DIFF[saved.current.diff]} · ${fmt(saved.elapsed||0)}</span></button>`:''}<section class="cards">
<button class="game-card" data-g="queens"><span class="game-icon">♛</span><span><h2>Queens</h2><p>Une reine par ligne, colonne et zone.</p></span></button>
<button class="game-card" data-g="tango"><span class="game-icon">☀︎</span><span><h2>Tango</h2><p>Équilibre Soleil/Lune et relations.</p></span></button>
<button class="game-card" data-g="sudoku"><span class="game-icon">✎</span><span><h2>Mini Sudoku</h2><p>6×6, lignes, colonnes et régions.</p></span></button>
<button class="game-card" data-g="patches"><span class="game-icon">▦</span><span><h2>Patches</h2><p>Reconstitue toutes les zones.</p></span></button>
</section><button class="daily-card" id="dailyBtn"><span>◆</span><b>Défi quotidien</b><small>${dailyProgress()}/4 terminés aujourd’hui</small></button><button class="stats-card" id="statsBtn"><span>▥</span><b>Statistiques & progression</b><small>Historique, records et séries</small></button><button class="settings-card" id="settingsBtn"><span>⚙︎</span><b>Préférences</b><small>Thème, sons et données locales</small></button><div class="footer-note">Logic 4 v${VERSION} · Projet indépendant — sans affiliation à LinkedIn.</div>`;
if(saved)$('#resumeBtn').onclick=resumeSaved;$('#dailyBtn').onclick=dailyView;$('#statsBtn').onclick=statsView;$('#settingsBtn').onclick=settingsView;app.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>launch(b.dataset.g,'easy'));app.querySelectorAll('button').forEach(pressFeedback)}
function gameLabel(g){return {queens:'Queens',tango:'Tango',sudoku:'Mini Sudoku',patches:'Patches'}[g]||g}
function shell(name,subtitle,diff,content,rules){app.innerHTML=`<section class="panel"><div class="game-head"><div><h1>${name}</h1><p>${subtitle}${current&&current.rating?` · <span class="difficulty-meter">score ${current.rating.score} · ${current.rating.technique}</span>`:''}</p></div><select class="difficulty" id="difficulty" aria-label="Difficulté">${Object.entries(DIFF).filter(([k])=>current?.game==='queens'||k!=='expert').map(([k,v])=>`<option value="${k}" ${k===diff?'selected':''}>${v}</option>`).join('')}</select></div><div class="toolbar" aria-label="Actions"><button class="btn primary" id="newBtn">Nouvelle</button><button class="btn" id="pauseBtn">Pause</button><button class="btn" id="checkBtn">Vérifier</button><button class="btn" id="hintBtn">Indice</button><button class="btn secondary-action" id="solutionBtn">Solution</button><button class="btn secondary-action" id="rulesBtn">Règles</button></div><div id="status" class="status" aria-live="polite"></div>${content}<div class="rules">${rules}</div></section>`;
$('#difficulty').onchange=e=>launch(current.game,e.target.value);$('#newBtn').onclick=()=>launch(current.game,current.diff);$('#pauseBtn').onclick=togglePause;$('#rulesBtn').onclick=()=>modal(`Règles — ${name}`,rules);app.querySelectorAll('button').forEach(pressFeedback);updatePauseButton()}
function launch(game,diff){if(game!=='queens'&&diff==='expert')diff='hard';closePreviousAttempt();clearSaved();stopTimer();paused=false;setBusy(true);current={game,diff};requestAnimationFrame(()=>{try{if(game==='queens')queens(diff);if(game==='tango')tango(diff);if(game==='sudoku')sudoku(diff);if(game==='patches')patches(diff);statsStart(current);startTimer(true,0,false);saveCurrent();haptic(8)}finally{setBusy(false)}})}
function resumeSaved(){let s=getSaved();if(!s)return home();stopTimer();let c=s.current;c.givens=c.givens?new Set(c.givens):c.givens;c.empty=c.empty?new Set(c.empty):c.empty;current=c;if(c.game==='queens')renderQueens(c);if(c.game==='tango')renderTango(c);if(c.game==='sudoku')renderSudoku(c);if(c.game==='patches')renderPatches(c);startTimer(true,s.elapsed||0,!!s.paused);updatePauseButton();showToast('Partie restaurée')}

function hintStage(kind,target,message,apply){
  if(!current.hintFlow||current.hintFlow.kind!==kind||current.hintFlow.key!==target.join(','))current.hintFlow={kind,key:target.join(','),stage:0};
  let h=current.hintFlow;h.stage++;
  clearHintFocus();
  if(h.stage===1){focusHint(target);showToast(`Où regarder : ${message.where}`)}
  else if(h.stage===2){focusHint(target);showToast(`Logique : ${message.logic}`)}
  else{apply();current.hintFlow=null;showToast(message.reveal);haptic(12)}
  saveCurrent()
}
function focusHint([r,c]){let board=document.querySelector('.board');if(!board)return;let n=current.n||6,d=board.children[r*n+c];if(d)d.classList.add('hint-focus')}
function clearHintFocus(){document.querySelectorAll('.hint-focus').forEach(x=>x.classList.remove('hint-focus'))}
function touchSave(fn){return()=>{if(paused)return;current.hintFlow=null;clearHintFocus();fn();saveCurrent()}}
// QUEENS
const queenBases={easy:{sol:[1,3,5,0,2,4],reg:[[0,0,1,1,1,1],[0,1,1,1,1,1],[0,0,0,0,2,2],[3,4,4,4,2,2],[4,4,4,4,2,2],[4,4,4,4,5,2]]},medium:{sol:[2,5,1,4,0,3,6],reg:[[0,0,0,0,0,1,1],[2,0,6,6,6,1,6],[2,2,6,3,3,1,6],[2,2,6,5,3,1,6],[4,2,6,5,3,3,6],[4,2,6,5,5,5,6],[6,6,6,6,6,6,6]]},hard:{sol:[2,5,0,3,6,1,4,7],reg:[[0,0,0,0,0,4,4,4],[2,2,0,0,0,1,4,4],[2,7,7,4,4,4,4,4],[2,2,7,3,3,4,4,4],[5,2,7,6,3,4,4,7],[5,5,7,6,6,6,6,7],[7,7,7,7,6,6,7,7],[7,7,7,7,7,7,7,7]]}};
function queens(diff){let base=queenBases[diff],k=Math.floor(Math.random()*8),reg=transformGrid(base.reg,k),n=reg.length,queensSol=Array(n).fill(-1);let mask=base.sol.map((c,r)=>Array.from({length:n},(_,j)=>j===c?1:0));mask=transformGrid(mask,k);for(let r=0;r<n;r++)queensSol[r]=mask[r].indexOf(1);current={game:'queens',diff,n,reg,sol:queensSol,state:Array.from({length:n},()=>Array(n).fill(0)),completed:false};renderQueens(current)}


function solvedQ(){return !!current&&current.game==='queens'&&current.state.every((row,r)=>row[current.sol[r]]===2)&&current.state.flat().filter(v=>v===2).length===current.n}
function solvedT(){return !!current&&current.game==='tango'&&current.state.every((row,r)=>row.every((v,c)=>v===current.sol[r][c]))}
function solvedS(){return !!current&&current.game==='sudoku'&&current.state.every((row,r)=>row.every((v,c)=>v===current.sol[r][c]))}
function solvedP(){return !!current&&current.game==='patches'&&current.paint.every((row,r)=>row.every((v,c)=>v===current.reg[r][c]))}
function maybeAutoFinish(){
  if(!current||current.completed||paused)return false;
  let ok=current.game==='queens'?solvedQ():current.game==='tango'?solvedT():current.game==='sudoku'?solvedS():current.game==='patches'?solvedP():false;
  if(ok){finish(`Bravo ! ${gameLabel(current.game)} résolu.`);return true}
  return false
}
function celebrateBoard(){
  let board=document.querySelector('.board');if(!board)return;
  board.classList.add('board-complete');
  [...board.children].forEach((cell,i)=>{cell.style.setProperty('--win-delay',`${Math.min(i,80)*16}ms`);cell.classList.add('win-pop')});
  let layer=document.createElement('div');layer.className='celebration-layer';layer.setAttribute('aria-hidden','true');
  for(let i=0;i<22;i++){let p=document.createElement('i');p.style.setProperty('--x',`${8+Math.random()*84}%`);p.style.setProperty('--dx',`${-55+Math.random()*110}px`);p.style.setProperty('--delay',`${Math.random()*220}ms`);p.style.setProperty('--rot',`${Math.random()*500-250}deg`);layer.appendChild(p)}
  document.body.appendChild(layer);
  setTimeout(()=>{layer.remove();board?.classList.remove('board-complete');board?.querySelectorAll('.win-pop').forEach(x=>{x.classList.remove('win-pop');x.style.removeProperty('--win-delay')})},1700)
}
function queenAutoCrossEnabled(){return prefs().queenAutoCross===true}
function setQueenAutoCross(v){let p=prefs();p.queenAutoCross=!!v;savePrefs(p)}
function queenCrossCellsFor(r,c){
  let out=[],seen=new Set(),n=current.n,z=current.reg[r][c];
  function add(rr,cc){if(rr<0||cc<0||rr>=n||cc>=n||(rr===r&&cc===c))return;let k=rr+','+cc;if(!seen.has(k)){seen.add(k);out.push([rr,cc])}}
  for(let i=0;i<n;i++){add(r,i);add(i,c)}
  for(let rr=0;rr<n;rr++)for(let cc=0;cc<n;cc++)if(current.reg[rr][cc]===z)add(rr,cc)
  for(let rr=r-1;rr<=r+1;rr++)for(let cc=c-1;cc<=c+1;cc++)add(rr,cc)
  return out
}
function applyQueenAutoCross(r,c){
  if(!queenAutoCrossEnabled())return;
  for(let [rr,cc] of queenCrossCellsFor(r,c))if(current.state[rr][cc]!==2)current.state[rr][cc]=1
}
function setQueenCell(r,c,v){
  current.state[r][c]=v;
  if(v===2)applyQueenAutoCross(r,c)
}
function renderQueens(c){const colors=['#f6d68a','#c9dca5','#b9d8e9','#d9c4e8','#f3b8ad','#b5dbc9','#e7c9a3','#c6c7e9','#c4dfd7'];shell('Queens',`${c.n}×${c.n} · ${DIFF[c.diff]} · générée`,c.diff,`<div class="queen-options"><label class="switch-row"><input type="checkbox" id="queenAutoCross" ${queenAutoCrossEnabled()?'checked':''}><span>Croix automatiques quand je place une reine</span></label></div><div class="board-wrap"><div class="board" id="qboard" style="grid-template-columns:repeat(${c.n},minmax(0,1fr));grid-template-rows:repeat(${c.n},minmax(0,1fr))"></div></div><div class="legend">Touchez une case pour faire vide → X → reine. Faites glisser le doigt horizontalement ou verticalement pour poser des X.</div>`,`Place exactement une reine par ligne, par colonne et par zone colorée. Deux reines ne peuvent pas être dans des cases adjacentes, diagonales comprises.`);let b=$('#qboard'),dragging=false,pointerId=null,startCell=null,dragAxis=null,dragged=false,visited=new Set();
function cellFromPoint(x,y){let el=document.elementFromPoint(x,y);return el&&el.closest?el.closest('#qboard .cell'):null}
function markDragCell(d){if(!d)return;let r=+d.dataset.r,col=+d.dataset.c,k=r+','+col;if(visited.has(k)||current.state[r][col]===2)return;visited.add(k);if(startCell&&dragAxis){let sr=+startCell.dataset.r,sc=+startCell.dataset.c;if(dragAxis==='row'&&r!==sr)return;if(dragAxis==='col'&&col!==sc)return}current.hintFlow=null;clearHintFocus();current.state[r][col]=1;dragged=true;drawQ()}
for(let r=0;r<c.n;r++)for(let col=0;col<c.n;col++){let d=document.createElement('div');d.className='cell';d.style.background=colors[c.reg[r][col]%colors.length];d.dataset.r=r;d.dataset.c=col;
d.onpointerdown=e=>{if(paused)return;e.preventDefault();dragging=true;pointerId=e.pointerId;startCell=d;dragAxis=null;dragged=false;visited.clear();try{b.setPointerCapture(pointerId)}catch(_){}};
d.onpointermove=e=>{if(!dragging||e.pointerId!==pointerId)return;e.preventDefault();let hit=cellFromPoint(e.clientX,e.clientY);if(!hit)return;let sr=+startCell.dataset.r,sc=+startCell.dataset.c,hr=+hit.dataset.r,hc=+hit.dataset.c;if(!dragAxis&&(hr!==sr||hc!==sc))dragAxis=Math.abs(hc-sc)>=Math.abs(hr-sr)?'row':'col';if(dragAxis){markDragCell(startCell);markDragCell(hit)}};
b.appendChild(d)}
let endDrag=e=>{if(!dragging||e.pointerId!==pointerId)return;try{b.releasePointerCapture(pointerId)}catch(_){};let d=startCell;dragging=false;pointerId=null;if(!dragged&&d){let r=+d.dataset.r,col=+d.dataset.c;current.hintFlow=null;clearHintFocus();let next=(current.state[r][col]+1)%3;setQueenCell(r,col,next);haptic(next===2?16:7);drawQ()}else if(dragged){haptic(7)}saveCurrent();maybeAutoFinish();startCell=null;dragAxis=null;visited.clear()};
b.onpointerup=endDrag;b.onpointercancel=endDrag;
drawQ();$('#queenAutoCross').onchange=e=>{setQueenAutoCross(e.target.checked);if(e.target.checked){for(let r=0;r<current.n;r++)for(let col=0;col<current.n;col++)if(current.state[r][col]===2)applyQueenAutoCross(r,col);drawQ();saveCurrent();showToast('Croix automatiques activées')}else showToast('Croix automatiques désactivées')};$('#checkBtn').onclick=checkQ;$('#hintBtn').onclick=hintQ;$('#solutionBtn').onclick=()=>{if(paused)return;current.state=current.state.map((row,r)=>row.map((_,col)=>col===current.sol[r]?2:1));drawQ();finish('Solution affichée','revealed')}}
function drawQ(){[...$('#qboard').children].forEach((d,i)=>{let r=Math.floor(i/current.n),c=i%current.n,v=current.state[r][c];d.innerHTML=v===2?'<span class="queen">♛</span>':v===1?'<span class="mark">×</span>':'';d.classList.remove('error')})}
function checkQ(){if(solvedQ())finish('Bravo ! Queens résolu.');else status('Il reste une erreur ou une case à résoudre.',false)}
function hintQ(){if(paused)return;let a=[];for(let r=0;r<current.n;r++){let c=current.sol[r];if(current.state[r][c]!==2)a.push([r,c])}if(!a.length)return;let t=a[0],z=current.reg[t[0]][t[1]];hintStage('queens',t,{where:`observe la région ${z+1} et la ligne ${t[0]+1}.`,logic:'croise les cases encore possibles avec les colonnes et les régions déjà occupées.',reveal:'Une reine a été placée.'},()=>{setQueenCell(t[0],t[1],2);drawQ();maybeAutoFinish()})}

// TANGO
const tangoSolutions={easy:[[0,1,0,1,0,1],[1,0,1,0,1,0],[1,1,0,0,1,0],[0,0,1,1,0,1],[1,0,0,1,0,1],[0,1,1,0,1,0]],medium:[[0,1,0,0,1,1],[1,0,1,1,0,0],[0,0,1,0,1,1],[1,1,0,1,0,0],[0,1,1,0,0,1],[1,0,0,1,1,0]],hard:[[1,0,1,0,0,1],[0,1,0,1,1,0],[1,1,0,0,1,0],[0,0,1,1,0,1],[1,0,1,0,1,0],[0,1,0,1,0,1]]};
function tango(diff){let sol=transformGrid(tangoSolutions[diff],Math.floor(Math.random()*8)),n=6,givenCount={easy:12,medium:8,hard:5}[diff],relCount={easy:8,medium:10,hard:11}[diff],positions=shuffle(Array.from({length:36},(_,i)=>i)),givens=new Set(positions.slice(0,givenCount)),edges=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++){if(c<n-1)edges.push([r,c,'r',sol[r][c]===sol[r][c+1]?'=':'×']);if(r<n-1)edges.push([r,c,'d',sol[r][c]===sol[r+1][c]?'=':'×'])}edges=shuffle(edges).slice(0,relCount);let state=Array.from({length:n},()=>Array(n).fill(-1));for(let i of givens){let r=Math.floor(i/6),c=i%6;state[r][c]=sol[r][c]}current={game:'tango',diff,n,sol,givens,edges,state,completed:false};renderTango(current)}
function renderTango(c){shell('Tango','6×6 · Soleil & Lune · générée',c.diff,`<div class="board-wrap"><div class="board" id="tboard" style="grid-template-columns:repeat(6,minmax(0,1fr));grid-template-rows:repeat(6,minmax(0,1fr))"></div></div>`,`Remplis chaque case avec ☀ ou ☾. Chaque ligne et colonne doit contenir 3 de chaque. Jamais plus de deux symboles identiques consécutifs. « = » impose deux symboles identiques ; « × » deux symboles différents.`);let b=$('#tboard');for(let r=0;r<6;r++)for(let col=0;col<6;col++){let d=document.createElement('div');d.className='cell'+(c.givens.has(r*6+col)?' fixed':'');d.dataset.r=r;d.dataset.c=col;if(!c.givens.has(r*6+col))d.onclick=touchSave(()=>{current.state[r][col]=(current.state[r][col]+2)%3-1;haptic(8);drawT();maybeAutoFinish()});b.appendChild(d)}drawT();$('#checkBtn').onclick=checkT;$('#hintBtn').onclick=hintT;$('#solutionBtn').onclick=()=>{if(paused)return;current.state=current.sol.map(r=>[...r]);drawT();finish('Solution affichée','revealed')}}
function drawT(){let b=$('#tboard');[...b.children].forEach((d,i)=>{let r=Math.floor(i/6),c=i%6,v=current.state[r][c];d.innerHTML=v===0?'<span class="tango-symbol">☾</span>':v===1?'<span class="tango-symbol">☀</span>':''});current.edges.forEach(([r,c,dir,s])=>{let d=b.children[r*6+c];let e=document.createElement('span');e.className='relation '+dir;e.textContent=s;d.appendChild(e)})}
function checkT(){if(solvedT())finish('Bravo ! Tango résolu.');else status('La grille ne respecte pas encore toutes les règles.',false)}
function hintT(){if(paused)return;let a=[];for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(current.state[r][c]!==current.sol[r][c]&&!current.givens.has(r*6+c))a.push([r,c]);if(!a.length)return;let t=a[0];hintStage('tango',t,{where:`regarde la case ligne ${t[0]+1}, colonne ${t[1]+1} et ses voisines.`,logic:'utilise d’abord une relation =/× éventuelle, puis la règle 3/3 et l’interdiction de trois symboles identiques.',reveal:'Une case a été révélée.'},()=>{current.state[t[0]][t[1]]=current.sol[t[0]][t[1]];drawT();maybeAutoFinish()})}

// MINI SUDOKU 6x6 regions 2x3
const sudBase=[[1,2,3,4,5,6],[4,5,6,1,2,3],[2,3,4,5,6,1],[5,6,1,2,3,4],[3,4,5,6,1,2],[6,1,2,3,4,5]];
function countMiniSudoku(grid,limit=2){let n=6,count=0;function valid(r,c,v){for(let i=0;i<n;i++)if(grid[r][i]===v||grid[i][c]===v)return false;let br=Math.floor(r/2)*2,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+2;rr++)for(let cc=bc;cc<bc+3;cc++)if(grid[rr][cc]===v)return false;return true}function bt(){if(count>=limit)return;let best=null,bestCand=null;for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(grid[r][c]===0){let cand=[];for(let v=1;v<=6;v++)if(valid(r,c,v))cand.push(v);if(!cand.length)return;if(!best||cand.length<bestCand.length){best=[r,c];bestCand=cand;if(cand.length===1)break}}if(!best){count++;return}let [r,c]=best;for(let v of bestCand){grid[r][c]=v;bt();grid[r][c]=0;if(count>=limit)return}}bt();return count}
function makeSudokuHoles(sol,target){let puzzle=sol.map(r=>[...r]),order=shuffle(Array.from({length:36},(_,i)=>i)),holes=[];for(let i of order){if(holes.length>=target)break;let r=Math.floor(i/6),c=i%6,old=puzzle[r][c];puzzle[r][c]=0;if(countMiniSudoku(puzzle.map(x=>[...x]),2)===1)holes.push(i);else puzzle[r][c]=old}return new Set(holes)}
function sudoku(diff){let map=shuffle([1,2,3,4,5,6]),sol=sudBase.map(r=>r.map(v=>map[v-1]));if(Math.random()<.5)sol=sol.map(r=>[...r].reverse());if(Math.random()<.5)sol=[...sol].reverse();let holes={easy:16,medium:22,hard:27}[diff],empty=makeSudokuHoles(sol,holes);current={game:'sudoku',diff,n:6,sol,empty,state:sol.map((r,ri)=>r.map((v,c)=>empty.has(ri*6+c)?0:v)),sel:null,completed:false};renderSudoku(current)}
function renderSudoku(c){shell('Mini Sudoku','6×6 · chiffres 1 à 6 · générée',c.diff,`<div class="board-wrap"><div class="board sudoku" id="sboard" style="grid-template-columns:repeat(6,minmax(0,1fr));grid-template-rows:repeat(6,minmax(0,1fr))"></div></div><div class="numpad" id="numpad">${[1,2,3,4,5,6].map(n=>`<button data-n="${n}">${n}</button>`).join('')}<button data-n="0" aria-label="Effacer">⌫</button></div>`,`Complète la grille avec 1 à 6. Chaque ligne, chaque colonne et chaque région 2×3 doit contenir les six chiffres exactement une fois.`);let b=$('#sboard');for(let r=0;r<6;r++)for(let col=0;col<6;col++){let fixed=!c.empty.has(r*6+col),d=document.createElement('div');d.className='cell '+(fixed?'fixed ':'')+((col===2)?'boxR ':'')+((r===1||r===3)?'boxB ':'');if(!fixed)d.onclick=touchSave(()=>{current.sel=[r,col];drawS()});b.appendChild(d)}$('#numpad').querySelectorAll('button').forEach(bt=>bt.onclick=touchSave(()=>{if(current.sel){let [r,col]=current.sel;current.state[r][col]=+bt.dataset.n;haptic(8);drawS();maybeAutoFinish()}}));drawS();$('#checkBtn').onclick=checkS;$('#hintBtn').onclick=hintS;$('#solutionBtn').onclick=()=>{if(paused)return;current.state=current.sol.map(r=>[...r]);drawS();finish('Solution affichée','revealed')}}
function drawS(){let sel=current.sel,sv=sel?current.state[sel[0]][sel[1]]:0;[...$('#sboard').children].forEach((d,i)=>{let r=Math.floor(i/6),c=i%6,v=current.state[r][c];d.textContent=v||'';let sameUnit=!!sel&&(r===sel[0]||c===sel[1]||(Math.floor(r/2)===Math.floor(sel[0]/2)&&Math.floor(c/3)===Math.floor(sel[1]/3)));d.classList.toggle('peer',sameUnit&&!(r===sel[0]&&c===sel[1]));d.classList.toggle('same-value',!!sv&&v===sv&&!(r===sel[0]&&c===sel[1]));d.classList.toggle('selected',!!sel&&sel[0]===r&&sel[1]===c);d.classList.remove('error')})}
function checkS(){if(solvedS())finish('Bravo ! Mini Sudoku résolu.');else status('Il reste une erreur ou une case vide.',false)}
function hintS(){if(paused)return;let a=[];for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(current.state[r][c]!==current.sol[r][c]&&current.empty.has(r*6+c))a.push([r,c]);if(!a.length)return;let t=a[0];hintStage('sudoku',t,{where:`étudie la case ligne ${t[0]+1}, colonne ${t[1]+1}.`,logic:'élimine les chiffres déjà présents dans sa ligne, sa colonne et son bloc 2×3.',reveal:'Un chiffre a été révélé.'},()=>{current.state[t[0]][t[1]]=current.sol[t[0]][t[1]];current.sel=t;drawS();maybeAutoFinish()})}

// PATCHES — connected target regions; player paints each clue region.
const patchDefs={
easy:{n:5,reg:[[0,0,1,1,1],[0,0,1,2,2],[3,3,3,2,2],[3,4,4,4,5],[3,4,5,5,5]]},
medium:{n:6,reg:[[0,0,1,1,1,2],[0,3,3,1,2,2],[0,3,4,4,4,2],[5,3,4,6,6,6],[5,5,7,7,6,8],[5,7,7,8,8,8]]},
hard:{n:7,reg:[[0,0,1,1,1,2,2],[0,3,3,1,2,2,4],[0,3,5,5,5,4,4],[6,3,5,7,7,7,4],[6,6,5,8,7,9,9],[6,10,10,8,8,9,11],[10,10,8,8,11,11,11]]}};
function patchShape(cells){let rs=cells.map(x=>x[0]),cs=cells.map(x=>x[1]),h=Math.max(...rs)-Math.min(...rs)+1,w=Math.max(...cs)-Math.min(...cs)+1,rect=h*w===cells.length;if(!rect)return 'libre';if(h===w)return 'carré';return h>w?'vertical':'horizontal'}
function patches(diff){let def=patchDefs[diff],reg=transformGrid(def.reg,Math.floor(Math.random()*8)),n=reg.length,ids=[...new Set(reg.flat())],cellsBy={};ids.forEach(id=>cellsBy[id]=[]);for(let r=0;r<n;r++)for(let c=0;c<n;c++)cellsBy[reg[r][c]].push([r,c]);let clues={};ids.forEach(id=>{let cells=cellsBy[id],p=cells[Math.floor(cells.length/2)],mode=diff==='easy'?'both':diff==='medium'?(Math.random()<.5?'size':'shape'):(Math.random()<.45?'shape':Math.random()<.8?'size':'none');clues[id]={pos:p,size:cells.length,shape:patchShape(cells),mode}});const pal=['#f3c6a8','#b9d9c1','#c6d4ed','#e2c3df','#f0dc9d','#c7e0e3','#d5ceb8','#d4e3b4','#edbfc1','#c8c4e8','#e5d0a4','#b7d7d1'];current={game:'patches',diff,n,reg,ids,cellsBy,clues,pal,active:ids[0],paint:Array.from({length:n},()=>Array(n).fill(null)),completed:false};renderPatches(current)}
function renderPatches(c){shell('Patches',`${c.n}×${c.n} · générée · reconstruis les zones`,c.diff,`<div class="patch-palette" id="patchPalette"></div><div class="board-wrap"><div class="board" id="pboard" style="grid-template-columns:repeat(${c.n},minmax(0,1fr));grid-template-rows:repeat(${c.n},minmax(0,1fr))"></div></div><div class="legend">Choisis un indice, puis touche les cases de sa zone. Tu peux aussi faire glisser le doigt pour peindre plusieurs cases.</div>`,`Remplis toute la grille avec des zones sans chevauchement. Chaque zone contient exactement une case-indice. Un indice peut donner la taille, la forme (carré, vertical ou horizontal), les deux, ou aucun.`);let pp=$('#patchPalette');c.ids.forEach(id=>{let bt=document.createElement('button');bt.className='patch-chip';bt.style.background=c.pal[id%c.pal.length];bt.dataset.id=id;bt.textContent=`Zone ${id+1}`;bt.onclick=touchSave(()=>{current.active=+bt.dataset.id;drawP()});pp.appendChild(bt)});let b=$('#pboard'),painting=false,paintValue=true,pointerId=null;function paintCell(r,col){if(paused)return;let target=paintValue?current.active:null;if(current.paint[r][col]!==target){current.paint[r][col]=target;drawP();saveCurrent();maybeAutoFinish()}}function paintAtPoint(x,y){let el=document.elementFromPoint(x,y)?.closest('.patch-cell');if(el&&b.contains(el))paintCell(+el.dataset.r,+el.dataset.c)}for(let r=0;r<c.n;r++)for(let col=0;col<c.n;col++){let d=document.createElement('div');d.className='cell patch-cell';d.dataset.r=r;d.dataset.c=col;d.onpointerdown=e=>{if(paused)return;e.preventDefault();painting=true;pointerId=e.pointerId;paintValue=current.paint[r][col]!==current.active;haptic(7);try{b.setPointerCapture(pointerId)}catch(_){}paintCell(r,col)};b.appendChild(d)}b.onpointermove=e=>{if(painting&&e.pointerId===pointerId){e.preventDefault();paintAtPoint(e.clientX,e.clientY)}};let endPaint=e=>{if(e.pointerId===pointerId){painting=false;try{b.releasePointerCapture(pointerId)}catch(_){}pointerId=null}};b.onpointerup=endPaint;b.onpointercancel=endPaint;drawP();$('#checkBtn').onclick=checkP;$('#hintBtn').onclick=hintP;$('#solutionBtn').onclick=()=>{if(paused)return;current.paint=current.reg.map(r=>[...r]);drawP();finish('Solution affichée','revealed')}}
function clueHTML(cl){let parts=[];if(cl.mode==='both'||cl.mode==='size')parts.push(`<b>${cl.size}</b>`);if(cl.mode==='both'||cl.mode==='shape')parts.push(`<span>${cl.shape==='carré'?'□':cl.shape==='vertical'?'▯':cl.shape==='horizontal'?'▭':'✣'}</span>`);if(cl.mode==='none')parts.push('<b>?</b>');return `<span class="patch-clue">${parts.join('')}</span>`}
function drawP(){let b=$('#pboard');[...b.children].forEach((d,i)=>{let r=Math.floor(i/current.n),c=i%current.n,p=current.paint[r][c];d.style.background=p===null?'#fff':current.pal[p%current.pal.length];d.classList.toggle('paint',p!==null);d.innerHTML='';d.classList.remove('clue');for(let id of current.ids){let [rr,cc]=current.clues[id].pos;if(rr===r&&cc===c){d.classList.add('clue');d.innerHTML=clueHTML(current.clues[id]);break}}});$('#patchPalette').querySelectorAll('.patch-chip').forEach(x=>x.classList.toggle('active',+x.dataset.id===current.active))}
function checkP(){let n=current.n,all=current.paint.every(row=>row.every(v=>v!==null));if(!all){status('Toutes les cases doivent appartenir à une zone.',false);return}let cluePositions=new Map(current.ids.map(id=>[current.clues[id].pos.join(','),id]));for(let id of current.ids){let cells=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(current.paint[r][c]===id)cells.push([r,c]);if(!cells.length){status('Chaque indice doit avoir une zone.',false);return}let own=current.clues[id].pos;if(!cells.some(([r,c])=>r===own[0]&&c===own[1])){status('Chaque zone doit contenir son propre indice.',false);return}let other=cells.some(([r,c])=>cluePositions.has(r+','+c)&&cluePositions.get(r+','+c)!==id);if(other){status('Une zone ne peut pas contenir deux indices.',false);return}let seen=new Set([cells[0].join(',')]),q=[cells[0]],set=new Set(cells.map(x=>x.join(',')));while(q.length){let [r,c]=q.pop();for(let [rr,cc] of [[r+1,c],[r-1,c],[r,c+1],[r,c-1]]){let k=rr+','+cc;if(set.has(k)&&!seen.has(k)){seen.add(k);q.push([rr,cc])}}}if(seen.size!==cells.length){status('Chaque zone doit être d’un seul tenant.',false);return}let cl=current.clues[id],sh=patchShape(cells);if(sh==='libre'){status('Chaque zone doit former un rectangle.',false);return}if((cl.mode==='both'||cl.mode==='size')&&cells.length!==cl.size){status('La taille d’une zone ne correspond pas à son indice.',false);return}if((cl.mode==='both'||cl.mode==='shape')&&sh!==cl.shape){status('La forme d’une zone ne correspond pas à son indice.',false);return}}finish('Bravo ! Patches résolu.')}
function hintP(){if(paused)return;let bad=[];for(let r=0;r<current.n;r++)for(let c=0;c<current.n;c++)if(current.paint[r][c]!==current.reg[r][c])bad.push([r,c]);if(!bad.length)return;let t=bad[0],id=current.reg[t[0]][t[1]],cl=current.clues[id];hintStage('patches',t,{where:`observe l’indice de la zone ${id+1} et les cases autour.`,logic:`teste les rectangles compatibles avec ${cl.mode==='size'||cl.mode==='both'?'la taille '+cl.size:'sa forme'} sans recouvrir un autre indice.`,reveal:'Une case de la zone a été révélée.'},()=>{current.paint[t[0]][t[1]]=id;drawP();maybeAutoFinish()})}
// ===== v1.2 generators: generated puzzles + uniqueness checks =====
function countQueensGenerated(reg,limit=2){const n=reg.length;let count=0,usedC=new Set(),usedR=new Set();function bt(r,prev){if(count>=limit)return;if(r===n){count++;return}for(let c=0;c<n;c++){let z=reg[r][c];if(usedC.has(c)||usedR.has(z))continue;if(r>0&&Math.abs(c-prev)===1)continue;usedC.add(c);usedR.add(z);bt(r+1,c);usedC.delete(c);usedR.delete(z);if(count>=limit)return}}bt(0,-99);return count}
function randomQueenSolution(n){for(let t=0;t<3000;t++){let p=shuffle(Array.from({length:n},(_,i)=>i));if(p.every((c,r)=>r===0||Math.abs(c-p[r-1])!==1))return p}return null}
function queenRegionsFromSolution(sol,singleCount){const n=sol.length,singleRows=new Set(shuffle(Array.from({length:n},(_,i)=>i)).slice(0,singleCount)),reg=Array.from({length:n},()=>Array(n).fill(-1));for(let r=0;r<n;r++)reg[r][sol[r]]=r;let left=n*n-n;while(left){let options=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(reg[r][c]===-1){let ids=[];for(let [rr,cc] of [[r+1,c],[r-1,c],[r,c+1],[r,c-1]])if(rr>=0&&rr<n&&cc>=0&&cc<n&&reg[rr][cc]>=0&&!singleRows.has(reg[rr][cc])&&!ids.includes(reg[rr][cc]))ids.push(reg[rr][cc]);if(ids.length)options.push([r,c,ids])}if(!options.length)return null;let [r,c,ids]=options[Math.floor(Math.random()*options.length)],sizes=Array(n).fill(0);for(let row of reg)for(let x of row)if(x>=0)sizes[x]++;ids.sort((a,b)=>sizes[a]-sizes[b]);let pool=ids.slice(0,Math.min(2,ids.length)),id=pool[Math.floor(Math.random()*pool.length)];reg[r][c]=id;left--}return reg}
function generateQueensPuzzle(diff){const n={easy:6,medium:7,hard:8,expert:9}[diff],single={easy:4,medium:3,hard:2,expert:3}[diff];for(let t=0;t<(diff==='expert'?1400:diff==='hard'?700:240);t++){let sol=randomQueenSolution(n);if(!sol)continue;let reg=queenRegionsFromSolution(sol,single);if(reg&&countQueensGenerated(reg,2)===1)return {n,sol,reg}}throw new Error('Queens generation failed')}
function queens(diff){let g=generateQueensPuzzle(diff);current={game:'queens',diff,n:g.n,reg:g.reg,sol:g.sol,state:Array.from({length:g.n},()=>Array(g.n).fill(0)),generated:true,unique:true,completed:false};renderQueens(current)}

const tangoValidRows=(()=>{let rows=[];for(let m=0;m<64;m++){let a=Array.from({length:6},(_,i)=>(m>>(5-i))&1);if(a.reduce((x,y)=>x+y,0)!==3)continue;if([0,1,2,3].some(i=>a[i]===a[i+1]&&a[i]===a[i+2]))continue;rows.push(a)}return rows})();
function generateTangoSolution(){let grid=[];function partialOK(row){for(let c=0;c<6;c++){let col=grid.map(r=>r[c]).concat(row[c]);let ones=col.reduce((a,b)=>a+b,0);if(ones>3||col.length-ones>3)return false;let L=col.length;if(L>=3&&col[L-1]===col[L-2]&&col[L-1]===col[L-3])return false}return true}function bt(r){if(r===6)return true;for(let row of shuffle(tangoValidRows)){if(!partialOK(row))continue;grid.push(row);if(bt(r+1))return true;grid.pop()}return false}bt(0);return grid.map(r=>[...r])}
function tangoEdgeValue(sol,r,c,d){let a=sol[r][c],b=d==='r'?sol[r][c+1]:sol[r+1][c];return a===b?'=':'×'}
function countTangoSolutions(givens,edges,limit=2){let grid=Array.from({length:6},()=>Array(6).fill(-1)),count=0;for(let i of givens.keys()){let r=Math.floor(i/6),c=i%6;grid[r][c]=givens.get(i)}function partial(r,c,v){for(let [rr,cc,d,s] of edges){let r2=d==='r'?rr:rr+1,c2=d==='r'?cc+1:cc;if((rr===r&&cc===c)||(r2===r&&c2===c)){let other=(rr===r&&cc===c)?grid[r2][c2]:grid[rr][cc];if(other!==-1&&((s==='='&&v!==other)||(s==='×'&&v===other)))return false}}let row=grid[r].slice();row[c]=v;let ones=row.filter(x=>x===1).length,zeros=row.filter(x=>x===0).length;if(ones>3||zeros>3)return false;for(let i=0;i<4;i++)if(row[i]!==-1&&row[i]===row[i+1]&&row[i]===row[i+2])return false;let col=grid.map((x,rr)=>rr===r?v:x[c]),co=col.filter(x=>x===1).length,cz=col.filter(x=>x===0).length;if(co>3||cz>3)return false;for(let i=0;i<4;i++)if(col[i]!==-1&&col[i]===col[i+1]&&col[i]===col[i+2])return false;return true}function bt(){if(count>=limit)return;let best=null,bestVals=null;for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(grid[r][c]===-1){let vals=[0,1].filter(v=>partial(r,c,v));if(!vals.length)return;if(!best||vals.length<bestVals.length){best=[r,c];bestVals=vals;if(vals.length===1)break}}if(!best){count++;return}let [r,c]=best;for(let v of bestVals){grid[r][c]=v;bt();grid[r][c]=-1;if(count>=limit)return}}bt();return count}
function generateTangoPuzzle(diff){for(let attempt=0;attempt<80;attempt++){let sol=generateTangoSolution(),all=[];for(let i=0;i<36;i++)all.push({t:'g',i,v:sol[Math.floor(i/6)][i%6]});for(let r=0;r<6;r++)for(let c=0;c<6;c++){if(c<5)all.push({t:'e',e:[r,c,'r',tangoEdgeValue(sol,r,c,'r')]});if(r<5)all.push({t:'e',e:[r,c,'d',tangoEdgeValue(sol,r,c,'d')]})}let giv=new Map(),edges=[],order=shuffle(all),minClues={easy:15,medium:12,hard:10}[diff];for(let clue of order){if(clue.t==='g')giv.set(clue.i,clue.v);else edges.push(clue.e);if(giv.size+edges.length>=minClues&&countTangoSolutions(giv,edges,2)===1)break}if(countTangoSolutions(giv,edges,2)!==1)continue;let removals=shuffle([...giv.keys()].map(i=>({t:'g',i})).concat(edges.map((e,i)=>({t:'e',e,i}))));for(let rm of removals){if(giv.size+edges.length<=minClues)break;if(rm.t==='g'){let v=giv.get(rm.i);giv.delete(rm.i);if(countTangoSolutions(giv,edges,2)!==1)giv.set(rm.i,v)}else{let idx=edges.findIndex(e=>e.join('|')===rm.e.join('|'));if(idx<0)continue;let old=edges.splice(idx,1)[0];if(countTangoSolutions(giv,edges,2)!==1)edges.splice(idx,0,old)}}return {sol,givens:new Set(giv.keys()),edges}}throw new Error('Tango generation failed')}
function tango(diff){let g=generateTangoPuzzle(diff),state=Array.from({length:6},()=>Array(6).fill(-1));for(let i of g.givens){let r=Math.floor(i/6),c=i%6;state[r][c]=g.sol[r][c]}current={game:'tango',diff,n:6,sol:g.sol,givens:g.givens,edges:g.edges,state,generated:true,unique:true,completed:false};renderTango(current)}

function randomSudokuSolution(){let bands=shuffle([[0,1],[2,3],[4,5]]),rows=bands.flatMap(b=>shuffle(b)),stacks=shuffle([[0,1,2],[3,4,5]]),cols=stacks.flatMap(s=>shuffle(s)),map=shuffle([1,2,3,4,5,6]);return rows.map(r=>cols.map(c=>map[sudBase[r][c]-1]))}
function sudoku(diff){let sol=randomSudokuSolution(),holes={easy:16,medium:22,hard:27}[diff],empty=makeSudokuHoles(sol,holes),actual=empty.size;if(actual<Math.min(holes-2,20)){sol=randomSudokuSolution();empty=makeSudokuHoles(sol,holes);actual=empty.size}current={game:'sudoku',diff,n:6,sol,empty,state:sol.map((r,ri)=>r.map((v,c)=>empty.has(ri*6+c)?0:v)),sel:null,generated:true,unique:countMiniSudoku(sol.map((r,ri)=>r.map((v,c)=>empty.has(ri*6+c)?0:v)),2)===1,completed:false};renderSudoku(current)}

function makeRectTiling(n,target){let targetCount=target[0]+Math.floor(Math.random()*(target[1]-target[0]+1)),rects=[{r:0,c:0,h:n,w:n}];let guard=0;while(rects.length<targetCount&&guard++<300){let candidates=rects.map((x,i)=>[x,i]).filter(([x])=>x.h>1||x.w>1);if(!candidates.length)break;let [rect,idx]=candidates[Math.floor(Math.random()*candidates.length)],splits=[];if(rect.h>1)for(let k=1;k<rect.h;k++)splits.push(['h',k]);if(rect.w>1)for(let k=1;k<rect.w;k++)splits.push(['w',k]);let [dir,k]=splits[Math.floor(Math.random()*splits.length)],a,b;if(dir==='h'){a={r:rect.r,c:rect.c,h:k,w:rect.w};b={r:rect.r+k,c:rect.c,h:rect.h-k,w:rect.w}}else{a={r:rect.r,c:rect.c,h:rect.h,w:k};b={r:rect.r,c:rect.c+k,h:rect.h,w:rect.w-k}}rects.splice(idx,1,a,b)}if(rects.length!==targetCount)return null;let reg=Array.from({length:n},()=>Array(n).fill(-1));rects.forEach((x,id)=>{x.id=id;for(let r=x.r;r<x.r+x.h;r++)for(let c=x.c;c<x.c+x.w;c++)reg[r][c]=id});return {reg,rects}}
function rectShape(h,w){return h===w?'carré':h>w?'vertical':'horizontal'}
function possiblePatchRects(n,clue,allCluePos){let out=[];for(let r0=0;r0<n;r0++)for(let r1=r0;r1<n;r1++)for(let c0=0;c0<n;c0++)for(let c1=c0;c1<n;c1++){if(clue.pos[0]<r0||clue.pos[0]>r1||clue.pos[1]<c0||clue.pos[1]>c1)continue;let h=r1-r0+1,w=c1-c0+1,area=h*w,shape=rectShape(h,w);if((clue.mode==='both'||clue.mode==='size')&&area!==clue.size)continue;if((clue.mode==='both'||clue.mode==='shape')&&shape!==clue.shape)continue;let containsOther=false;for(let p of allCluePos)if(p!==clue.pos&&p[0]>=r0&&p[0]<=r1&&p[1]>=c0&&p[1]<=c1){containsOther=true;break}if(!containsOther){let cells=[];for(let r=r0;r<=r1;r++)for(let c=c0;c<=c1;c++)cells.push(r*n+c);out.push(cells)}}return out}
function countPatchSolutions(n,ids,clues,limit=2){let positions=ids.map(id=>clues[id].pos),opts={};for(let id of ids){opts[id]=possiblePatchRects(n,clues[id],positions);if(!opts[id].length)return 0}let count=0,covered=new Set();function bt(done){if(count>=limit)return;if(done.size===ids.length){if(covered.size===n*n)count++;return}let best=null,bestOpts=null;for(let id of ids)if(!done.has(id)){let avail=opts[id].filter(cells=>cells.every(x=>!covered.has(x)));if(!avail.length)return;if(!best||avail.length<bestOpts.length){best=id;bestOpts=avail;if(avail.length===1)break}}done.add(best);for(let cells of bestOpts){cells.forEach(x=>covered.add(x));bt(done);cells.forEach(x=>covered.delete(x));if(count>=limit)break}done.delete(best)}bt(new Set());return count}
function generatePatchesPuzzle(diff){let n={easy:5,medium:6,hard:7}[diff],range={easy:[6,8],medium:[8,10],hard:[10,12]}[diff];for(let attempt=0;attempt<160;attempt++){let til=makeRectTiling(n,range);if(!til)continue;let ids=til.rects.map(x=>x.id),clues={};for(let rect of til.rects){let cells=[];for(let r=rect.r;r<rect.r+rect.h;r++)for(let c=rect.c;c<rect.c+rect.w;c++)cells.push([r,c]);let pos=cells[Math.floor(Math.random()*cells.length)];clues[rect.id]={pos,size:rect.h*rect.w,shape:rectShape(rect.h,rect.w),mode:'both'}}if(countPatchSolutions(n,ids,clues,2)!==1)continue;let order=shuffle(ids),choices=diff==='easy'?['size','shape']:diff==='medium'?['size','shape','none']:['none','shape','size'];for(let id of order){let old=clues[id].mode;for(let mode of shuffle(choices)){clues[id].mode=mode;if(countPatchSolutions(n,ids,clues,2)===1)break;clues[id].mode=old}}if(countPatchSolutions(n,ids,clues,2)===1){let cellsBy={};for(let id of ids)cellsBy[id]=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)cellsBy[til.reg[r][c]].push([r,c]);return {n,reg:til.reg,ids,cellsBy,clues}}}throw new Error('Patches generation failed')}
function patches(diff){let g=generatePatchesPuzzle(diff);const pal=['#f3c6a8','#b9d9c1','#c6d4ed','#e2c3df','#f0dc9d','#c7e0e3','#d5ceb8','#d4e3b4','#edbfc1','#c8c4e8','#e5d0a4','#b7d7d1'];current={game:'patches',diff,n:g.n,reg:g.reg,ids:g.ids,cellsBy:g.cellsBy,clues:g.clues,pal,active:g.ids[0],paint:Array.from({length:g.n},()=>Array(g.n).fill(null)),generated:true,unique:true,completed:false};renderPatches(current)}

function keyboardInput(e){if(!current||paused||current.completed)return;if(current.game==='sudoku'&&current.sel){let n=Number(e.key);if(n>=1&&n<=6){let [r,c]=current.sel;if(current.empty.has(r*6+c)){current.state[r][c]=n;haptic(6);drawS();saveCurrent();maybeAutoFinish();e.preventDefault()}}else if(e.key==='Backspace'||e.key==='Delete'||e.key==='0'){let [r,c]=current.sel;if(current.empty.has(r*6+c)){current.state[r][c]=0;drawS();saveCurrent();e.preventDefault()}}}}
document.addEventListener('keydown',keyboardInput);
function status(t,ok){let s=$('#status');if(!s)return;s.textContent=t;s.className='status '+(ok?'ok':'bad');if(!ok)playTone('error')}
function finish(t,outcome='solved'){let total=timerSeconds(),snapshot=current?{...current}:null;stopTimer(false);elapsedBase=total;startedAt=0;paused=true;if(current){statsFinish(current,total,outcome);markDaily(current,outcome,total);current.completed=true}clearSaved();renderTimer();status(`${t} — ${fmt(elapsedBase)}`,true);updatePauseButton();if(outcome==='solved'&&snapshot)requestAnimationFrame(()=>{celebrateBoard();setTimeout(()=>victoryOverlay(snapshot,total),620)})}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&current&&!current.completed)saveCurrent()});window.addEventListener('pagehide',()=>{if(current&&!current.completed)saveCurrent()});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
applyPrefs();try{window.matchMedia('(prefers-color-scheme:dark)').addEventListener('change',()=>{if(prefs().theme==='auto')applyPrefs()})}catch(_){}home();


// ===== v1.3 — analyseurs de difficulté =====
function collectCandidates(factory,count){let out=[],guard=0;while(out.length<count&&guard++<count*4){try{out.push(factory())}catch(_){}}if(!out.length)throw new Error('generation failed');return out}
function targetPick(items,diff){items=items.filter(x=>x&&x.rating&&Number.isFinite(x.rating.score)).sort((a,b)=>a.rating.score-b.rating.score);if(!items.length)throw new Error('difficulty analysis failed');return diff==='easy'?items[0]:(diff==='hard'||diff==='expert')?items[items.length-1]:items[Math.floor((items.length-1)/2)]}
function labelTechnique(kind,level){const map={sudoku:['single nu','single caché','blocage logique'],tango:['équilibrage / trio','relation = / ×','chaîne de contraintes'],patches:['rectangle forcé','couverture forcée','enchaînement spatial'],queens:['contrainte ligne/zone','propagation croisée','recherche contrainte']};return map[kind][Math.min(level,2)]}
function analyzeSudoku(sol,empty){let g=sol.map((r,ri)=>r.map((v,c)=>empty.has(ri*6+c)?0:v)),steps=0,hidden=0;function cand(r,c){let s=new Set([1,2,3,4,5,6]);for(let i=0;i<6;i++){s.delete(g[r][i]);s.delete(g[i][c])}let br=Math.floor(r/2)*2,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+2;rr++)for(let cc=bc;cc<bc+3;cc++)s.delete(g[rr][cc]);return [...s]}let guard=0;while(g.some(r=>r.includes(0))&&guard++<100){let progress=false;for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(!g[r][c]){let a=cand(r,c);if(a.length===1){g[r][c]=a[0];steps++;progress=true}}if(progress)continue;let units=[];for(let r=0;r<6;r++)units.push(Array.from({length:6},(_,c)=>[r,c]));for(let c=0;c<6;c++)units.push(Array.from({length:6},(_,r)=>[r,c]));for(let br=0;br<6;br+=2)for(let bc=0;bc<6;bc+=3){let u=[];for(let r=br;r<br+2;r++)for(let c=bc;c<bc+3;c++)u.push([r,c]);units.push(u)}outer:for(let u of units)for(let v=1;v<=6;v++){let ps=u.filter(([r,c])=>!g[r][c]&&cand(r,c).includes(v));if(ps.length===1){g[ps[0][0]][ps[0][1]]=v;steps++;hidden++;progress=true;break outer}}if(!progress)break}let remain=g.flat().filter(x=>!x).length,level=remain?2:hidden?1:0,score=Math.round(steps+hidden*2+remain*5);return {score,technique:labelTechnique('sudoku',level),solved:remain===0,remain,level}}
function tangoLocalVals(grid,edges,r,c){let vals=[];for(let v of [0,1]){let row=grid[r].slice();row[c]=v;let ones=row.filter(x=>x===1).length,zeros=row.filter(x=>x===0).length;if(ones>3||zeros>3)continue;let bad=false;for(let i=0;i<4;i++)if(row[i]!==-1&&row[i]===row[i+1]&&row[i]===row[i+2])bad=true;let col=grid.map((x,rr)=>rr===r?v:x[c]),co=col.filter(x=>x===1).length,cz=col.filter(x=>x===0).length;if(co>3||cz>3)bad=true;for(let i=0;i<4;i++)if(col[i]!==-1&&col[i]===col[i+1]&&col[i]===col[i+2])bad=true;for(let [rr,cc,d,s] of edges){let r2=d==='r'?rr:rr+1,c2=d==='r'?cc+1:cc;if((rr===r&&cc===c)||(r2===r&&c2===c)){let other=(rr===r&&cc===c)?grid[r2][c2]:grid[rr][cc];if(other!==-1&&((s==='='&&v!==other)||(s==='×'&&v===other)))bad=true}}if(!bad)vals.push(v)}return vals}
function analyzeTango(sol,givens,edges){let g=Array.from({length:6},()=>Array(6).fill(-1));for(let i of givens)g[Math.floor(i/6)][i%6]=sol[Math.floor(i/6)][i%6];let steps=0,rel=0,guard=0;while(g.flat().includes(-1)&&guard++<100){let progress=false;for(let [r,c,d,s] of edges){let r2=d==='r'?r:r+1,c2=d==='r'?c+1:c,a=g[r][c],b=g[r2][c2];if(a!==-1&&b===-1){g[r2][c2]=s==='='?a:1-a;steps++;rel++;progress=true}else if(b!==-1&&a===-1){g[r][c]=s==='='?b:1-b;steps++;rel++;progress=true}}for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(g[r][c]===-1){let vals=tangoLocalVals(g,edges,r,c);if(vals.length===1){g[r][c]=vals[0];steps++;progress=true}}if(!progress)break}let remain=g.flat().filter(x=>x===-1).length,level=remain?2:rel?1:0,score=Math.round(steps+rel*1.5+remain*3);return {score,technique:labelTechnique('tango',level),solved:remain===0,remain,level}}
function analyzePatches(n,ids,clues){let positions=ids.map(id=>clues[id].pos),opts={};for(let id of ids)opts[id]=possiblePatchRects(n,clues[id],positions);let chosen=new Map(),covered=new Set(),steps=0,coverForced=0,guard=0;while(chosen.size<ids.length&&guard++<100){let progress=false;for(let id of ids)if(!chosen.has(id)){let a=opts[id].filter(c=>c.every(x=>!covered.has(x)));if(a.length===1){chosen.set(id,a[0]);a[0].forEach(x=>covered.add(x));steps++;progress=true}}if(progress)continue;for(let cell=0;cell<n*n;cell++)if(!covered.has(cell)){let owners=[];for(let id of ids)if(!chosen.has(id))for(let cells of opts[id])if(cells.includes(cell)&&cells.every(x=>!covered.has(x)))owners.push([id,cells]);let uniq=[...new Set(owners.map(x=>x[0]))];if(uniq.length===1){let id=uniq[0],arr=owners.filter(x=>x[0]===id);if(arr.length===1){chosen.set(id,arr[0][1]);arr[0][1].forEach(x=>covered.add(x));steps++;coverForced++;progress=true;break}}}if(!progress)break}let remain=ids.length-chosen.size,level=remain?2:coverForced?1:0,branch=ids.reduce((s,id)=>s+Math.max(0,opts[id].length-1),0),score=Math.round(steps+coverForced*2+remain*5+branch*.25);return {score,technique:labelTechnique('patches',level),solved:remain===0,remain,level}}
function queenSearchStats(reg){let n=reg.length,nodes=0,maxBranch=0;function bt(r,cols,zones,prev){nodes++;if(r===n)return true;let cand=[];for(let c=0;c<n;c++){let z=reg[r][c];if(cols.has(c)||zones.has(z)||(r>0&&Math.abs(c-prev)===1))continue;cand.push(c)}maxBranch=Math.max(maxBranch,cand.length);for(let c of cand){let z=reg[r][c];cols.add(c);zones.add(z);if(bt(r+1,cols,zones,c))return true;cols.delete(c);zones.delete(z)}return false}bt(0,new Set(),new Set(),-99);return {nodes,maxBranch}}
function analyzeQueens(reg){let n=reg.length,regionSizes={};for(let x of reg.flat())regionSizes[x]=(regionSizes[x]||0)+1;let singles=Object.values(regionSizes).filter(x=>x===1).length,stats=queenSearchStats(reg),score=Math.round((stats.nodes-n-1)*2+stats.maxBranch*3+(n-singles)*2);let level=score>220?2:score>70?1:0;return {score,technique:labelTechnique('queens',level),solved:true,remain:0,level,nodes:stats.nodes,singles}}
function queenCandidate(diff){let g=generateQueensPuzzle(diff);g.rating=analyzeQueens(g.reg);return g}
function tangoCandidate(diff){let g=generateTangoPuzzle(diff);g.rating=analyzeTango(g.sol,g.givens,g.edges);return g}
function sudokuCandidate(diff){let sol=randomSudokuSolution(),holes={easy:16,medium:22,hard:27}[diff],empty=makeSudokuHoles(sol,holes);return {sol,empty,rating:analyzeSudoku(sol,empty)}}
function patchesCandidate(diff){let g=generatePatchesPuzzle(diff);g.rating=analyzePatches(g.n,g.ids,g.clues);return g}
function queens(diff){let g=targetPick(collectCandidates(()=>queenCandidate(diff),diff==='expert'?16:diff==='hard'?14:6),diff);current={game:'queens',diff,n:g.n,reg:g.reg,sol:g.sol,rating:g.rating,state:Array.from({length:g.n},()=>Array(g.n).fill(0)),generated:true,unique:true,completed:false};renderQueens(current)}
function tango(diff){let g=targetPick(collectCandidates(()=>tangoCandidate(diff),6),diff),state=Array.from({length:6},()=>Array(6).fill(-1));for(let i of g.givens)state[Math.floor(i/6)][i%6]=g.sol[Math.floor(i/6)][i%6];current={game:'tango',diff,n:6,sol:g.sol,givens:g.givens,edges:g.edges,rating:g.rating,state,generated:true,unique:true,completed:false};renderTango(current)}
function sudoku(diff){let g=targetPick(collectCandidates(()=>sudokuCandidate(diff),8),diff),sol=g.sol,empty=g.empty;current={game:'sudoku',diff,n:6,sol,empty,rating:g.rating,state:sol.map((r,ri)=>r.map((v,c)=>empty.has(ri*6+c)?0:v)),sel:null,generated:true,unique:true,completed:false};renderSudoku(current)}
function patches(diff){let g=targetPick(collectCandidates(()=>patchesCandidate(diff),diff==='hard'?5:4),diff);const pal=['#f3c6a8','#b9d9c1','#c6d4ed','#e2c3df','#f0dc9d','#c7e0e3','#d5ceb8','#d4e3b4','#edbfc1','#c8c4e8','#e5d0a4','#b7d7d1'];current={game:'patches',diff,n:g.n,reg:g.reg,ids:g.ids,cellsBy:g.cellsBy,clues:g.clues,rating:g.rating,pal,active:g.ids[0],paint:Array.from({length:g.n},()=>Array(g.n).fill(null)),generated:true,unique:true,completed:false};renderPatches(current)}
